//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.RoleLogger.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetRecordUsers")]
	public partial class msdyn_GetRecordUsersRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string RecordType = "RecordType";
			public const string RecordId = "RecordId";
			public const string RecordTypeName = "RecordTypeName";
		}
		
		public const string ActionLogicalName = "msdyn_GetRecordUsers";
		
		public int RecordType
		{
			get
			{
				if (this.Parameters.Contains("RecordType"))
				{
					return ((int)(this.Parameters["RecordType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["RecordType"] = value;
			}
		}
		
		public string RecordId
		{
			get
			{
				if (this.Parameters.Contains("RecordId"))
				{
					return ((string)(this.Parameters["RecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordId"] = value;
			}
		}
		
		public string RecordTypeName
		{
			get
			{
				if (this.Parameters.Contains("RecordTypeName"))
				{
					return ((string)(this.Parameters["RecordTypeName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordTypeName"] = value;
			}
		}
		
		public msdyn_GetRecordUsersRequest()
		{
			this.RequestName = "msdyn_GetRecordUsers";
			this.RecordType = default(int);
			this.RecordId = default(string);
			this.RecordTypeName = default(string);
		}
	}
}