//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLaB.RoleLogger.Xrm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Post_Source
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ActionHub Post", 2)]
		ActionHubPost = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auto Post", 0)]
		AutoPost = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Manual Post", 1)]
		ManualPost = 2,
	}
}